openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Searching product
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Liste of searched product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multiple_products:
                  summary: Multi-product found
                  value:
                    - name: Lait
                      expiration_datetime: 2025-09-10T12:00:00Z
                      price: 2.5
                    - name: Pain
                      expiration_datetime: 2025-09-05T08:00:00Z
                      price: 1.2
                empty_list:
                  summary: No product found
                  value: []
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
      required:
        - name
        - expiration_datetime
        - price
  parameters:
    limit:
      name: limit
      in: query
      description: Maximum number of element
      required: false
      schema:
        type: integer
        example: 10
    q:
      name: q
      in: query
      description:
      required: false
      schema:
        type: string
        example: lait
